### ISSUE TITLE
The script fails with error - Index out of range - Help

### ISSUE THREAD

**Issue by ganbi** [ChrisCompy/InstallTools#3]
PS C:\Users\Administrator\Downloads> C:\Users\Administrator\Downloads\OfflineWebSitesFeeds.ps1
12/16/2015 2:24:35 AM - Feed file downloaded successfully from http://go.microsoft.com/?linkid=9823756 to C:\Users\Administrator\Downloads\WebProduc
tList.xml.
Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex"
At C:\Users\Administrator\Downloads\OfflineWebSitesFeeds.ps1:28 char:5
+     $startPos = $propertiesStr.IndexOf("http", $webSitesFeedPos)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
12/16/2015 2:24:40 AM - Exception encountered when trying to download file from .
12/16/2015 2:24:40 AM - Error Message: The path is not of a legal form.
12/16/2015 2:24:40 AM - Exception encountered when trying to download file from .
12/16/2015 2:24:40 AM - Error Message: The path is not of a legal form.
12/16/2015 2:24:40 AM - Exception encountered when trying to download file from .
12/16/2015 2:24:40 AM - Error Message: The path is not of a legal form.
12/16/2015 2:24:40 AM - Exception encountered when trying to download file from .
12/16/2015 2:24:40 AM - Error Message: This operation is not supported for a relative URI.
12/16/2015 2:24:40 AM - Exception encountered when trying to download file from .
12/16/2015 2:24:40 AM - Error Message: This operation is not supported for a relative URI.
12/16/2015 2:24:40 AM - Exception encountered when trying to download file from .
12/16/2015 2:24:40 AM - Error Message: This operation is not supported for a relative URI

**Comment by JasonMorgan** [comment]
+1 this is my problem also.  I'll see if I can't fix it and submit a PR

**Comment by ozhgihinfa** [comment]
same issue

**Comment by Flodu31** [comment]
Same for me, any updates?

**Comment by ChrisCompy** [comment]
We added offline support directly in the websites.exe   You don't need to use this tool anymore.  With the offline capability that we have, you can create a zip of the offline install that you can easily move around.  Sorry for the confusion.  I should have updated this.
